// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'image': string;
  'question': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
