// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-checkbox-inner': string;
  'checkbox': string;
  'focused': string;
}
export const cssExports: CssExports;
export default cssExports;
