// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'draggableList': string;
  'handle': string;
  'handle-content': string;
}
export const cssExports: CssExports;
export default cssExports;
